%% Q6
% Write a script to calculate the cross-correlation function between two signals and 
% plot the crosscorrelation function with the correct axis. 
% Use the function xcorr or np.correlate and employ the correct scaling.

% Make a random signal by convolving 2 cycles of a sinusoid with a white, random signal generated by
% the procedure randn or np.random.randn. The sampling frequency should be 100 MHz, 
% the frequency of the sinusoid is 5 MHz, and the length of the random signal should be 20 microseconds.
% Make a delayed version of the signal by adding zeros at the start of the signals, so that the delay
% corresponds to 0.4 microseconds.

% Correlate the two random signals and find the delay from the maximum value in the cross-correlation
% function.
% Write a function that automatically determines the delay from the two signals and the relevant
% parameters (Hint: see help max). The delay must be given in seconds.
close all; clear; clc;

%%
close all; 

fs = 100*10^(6); % Sampling frequency (Hz)
f = 5*10^(6); % MHz sinusoid freq

Ts = 1/fs; % Sampling period (s)
T = 1/f;   % Period of the sinusoid

t = 0:Ts:2*T; % sinusoid
t_rand = 0:Ts:(20*10^(-6));

% White noise samples
nr = 20*10^(-6)*Ts;

sinusoid = sin(2*pi*f*t);
white_noise = randn(1,length(t_rand));

%% --- Plot sinusoid + noise ---
% figure;
% plot(t, sinusoid)
% hold on
% plot(t_rand, white_noise)
% 
% xlabel('Time (s)')
% ylabel('Amplitude')
% title('Sinusoid and White Noise')
% grid on

%% --- Convolution plot ---
conv_sig = conv(white_noise, sinusoid);

t_rand = 0:Ts:(length(conv_sig)-1)*Ts;

figure;
plot(t_rand, conv_sig, LineWidth=1.5)
xlabel('Time (s)', FontSize=22)
ylabel('Amplitude', FontSize=22)
title('Convolution of Noise and Sinusoid', FontSize=24)
grid on
xlim([0 (length(conv_sig)-1)*Ts])

% Delay
delay = 0.4*10^(-6); % (s)

Add_0 = delay*fs;

% Delays
delayed_conv_sig = [zeros(1,Add_0) conv_sig];
delayed_t_rand = 0:Ts:(length(delayed_conv_sig)-1)*Ts;

hold on;

plot(delayed_t_rand, delayed_conv_sig, LineWidth=1.5)
ylim([-max(abs(delayed_conv_sig)+3) max(abs(delayed_conv_sig)+3)])
xlim([0 max(delayed_t_rand)])


%% Cross-Correlate and plot using Auxillary Function
figure;

[corr, lags] = delay_cross_correlation(conv_sig, delayed_conv_sig);


%% Use function to find the Delay in seconds

[time_delay, delay_samples, corr_max, idx] = analyze_time_delay(corr, fs);